# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
  pull_request:
    branches: Features

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Run Instrumentation Tests (reactivecircus)
        uses: reactivecircus/android-emulator-runner@v2.6.1
        with:
            api-level: 23
            target: default
            arch: x86
            profile: Nexus 6
            script: ./gradlew connectedCheck --stacktrace 
      - name: Unit tests
        run: bash ./gradlew test --stacktrace;
        

